### ISSUE TITLE
IndexError: index ... is out of bounds for dimension 0 with size ...

### ISSUE THREAD

**Issue by xga0** [HKUDS/KGRec#1]
Thank you for sharing the code!

I tried KGCL on two datasets, and both reported similar errors:

alibaba-fashion:
```
index 30208 is out of bounds for dimension 0 with size 30040
Traceback (most recent call last):
  File "run_kgcl.py", line 154, in <module>
    ret = evaluator.test(model, user_dict, n_params)
  File ".../KGRec-main/utils/evaluator.py", line 139, in test
    u_g_embeddings = user_gcn_emb[user_batch]
IndexError: index 30208 is out of bounds for dimension 0 with size 30040
```

last-fm:
```
index 23566 is out of bounds for dimension 0 with size 23566
Traceback (most recent call last):
  File "run_kgcl.py", line 154, in <module>
    ret = evaluator.test(model, user_dict, n_params)
  File ".../KGRec-main/utils/evaluator.py", line 152, in test
    i_g_embddings = entity_gcn_emb[item_batch]
IndexError: index 23566 is out of bounds for dimension 0 with size 23566

```

**Comment by yuh-yang** [comment]
Hi,

Thanks for your feedback. It's now fixed
